<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AdminViewPromoCode.aspx.cs" Inherits="Online_Game_Store.AdminViewPromoCode" MasterPageFile="~/AdminPanel.Master" %>

<asp:Content ContentPlaceHolderID="ContentPlaceHolder1" ID="viewPlatformId" runat="server">
        <div  class="container">
            <asp:SqlDataSource ID="SqlDataSourcePromoView" runat="server" ConnectionString="<%$ ConnectionStrings:RegConnectionString %>" SelectCommand="SELECT * FROM [promo_code]" UpdateCommand="update [promo_code] set [code]=@code,[discount]=@discount,[status]=@status,[c_email]=@c_email,[end_date]=@end_date where [Id]=@Id" DeleteCommand="delete from [promo_code] where [Id]=@Id"></asp:SqlDataSource>
            <asp:GridView ID="GridViewPlatforms" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSourcePromoView" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="code" HeaderText="code" SortExpression="code" />
                    <asp:BoundField DataField="discount" HeaderText="discount" SortExpression="discount" />
                    <asp:BoundField DataField="status" HeaderText="status" SortExpression="status" />
                    <asp:BoundField DataField="c_email" HeaderText="c_email" SortExpression="c_email" />
                    <asp:BoundField DataField="end_date" HeaderText="end_date" SortExpression="end_date" />
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
        </div>
</asp:Content>