<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="viewDevelopers.aspx.cs" Inherits="Online_Game_Store.viewDevelopers" MasterPageFile="~/AdminPanel.Master" %>

<asp:Content ContentPlaceHolderID="ContentPlaceHolder1" ID="viewDevelopersId" runat="server">
       <nav class="navbar navbar-light bg-transparent">   
    <div class="container" >
 
            <asp:SqlDataSource ID="SqlDataSourceDevelopers" runat="server" ConnectionString="<%$ ConnectionStrings:RegConnectionString %>" SelectCommand="SELECT * FROM [developers]" UpdateCommand="update [developers] set [developer_title]=@developer_title where [developer_id]=@developer_id" DeleteCommand="delete from [developers] where [developer_id]=@developer_id"></asp:SqlDataSource>
        
        <asp:GridView  ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="developer_id" DataSourceID="SqlDataSourceDevelopers" ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="developer_id" HeaderText="developer_id" InsertVisible="False" ReadOnly="True" SortExpression="developer_id" />
                <asp:BoundField DataField="developer_title" HeaderText="developer_title" SortExpression="developer_title" />
            </Columns>
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>
         
             </div>
        </nav>
</asp:Content>