<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ViewProfileOrders.aspx.cs" Inherits="Online_Game_Store.ViewProfileOrders" MasterPageFile="~/Home.Master" %>

<asp:Content ContentPlaceHolderID="ContentPlaceHolder1" ID="ViewProfileOrdersID" runat="server">
    
    <table style="margin:0px;font-family:Arial;width:1200px;border: 2px solid black;" align="left">
        
        <tr >
           
            
            <td class="auto-style3" style="border: 2px solid black;background-color:#1f1f1f;text-align: left; width: 164px;">
                <asp:Button class="btn btn-outline-primary" ID="myAccount" runat="server" Text="My Account" Width="150px" CausesValidation="false" OnClick="myAccount_Click" />
            </td>
            <td class="auto-style3" style="border: 2px solid black;background-color:#1f1f1f;text-align: left; width: 164px;">
                <asp:Button class="btn btn-outline-primary" ID="Button1" runat="server" Text="Edit Account" Width="150px" CausesValidation="false" OnClick="Button1_Click" />
            </td>
             <td class="auto-style3" style="border: 2px solid black;background-color:#1f1f1f;text-align: left; width: 164px;">
                <asp:Button class="btn btn-outline-primary" ID="Button3" runat="server" Text="Promo Code" Width="150px" CausesValidation="false" OnClick="Button3_Click" />
            </td>
            <td class="auto-style3" style="border: 2px solid black;background-color:#1f1f1f;text-align: left; width: 164px;">
                <asp:Button class="btn btn-outline-danger" ID="Button1CustomerLogout" runat="server" Text="Logout" Width="150px" CausesValidation="false" OnClick="Button1CustomerLogout_Click" />
            </td>

        </tr>
        <tr >
          <td class="container" style="margin:0px;border: 2px solid black; width: 861px;background-image:url('Images/profile_image.jpg'); text-align: center;" colspan="4" align="center">
                <div  class="container" style="text-align: center">
                
                    <asp:SqlDataSource ID="SqlDataSourceViewProfileOrders" runat="server" ConnectionString="<%$ ConnectionStrings:RegConnectionString %>" SelectCommand="SELECT [Id], [card_number], [cardholder_name], [quantities], [total_price], [date], [status], [products] FROM [master_card_table] WHERE ([customer_email] = @customer_email)" DeleteCommand="DELETE FROM [master_card_table] WHERE ([customer_email] = @customer_email)">
                        <SelectParameters>
                            <asp:SessionParameter Name="customer_email" SessionField="c_email" Type="String" />
                        </SelectParameters>
                    </asp:SqlDataSource>
                    <div style="text-align: center">
                        <br />
                        <div class="auto-style2">
                    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSourceViewProfileOrders" ForeColor="#333333" GridLines="Vertical">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                            <asp:BoundField DataField="card_number" HeaderText="card_number" SortExpression="card_number" />
                            <asp:BoundField DataField="cardholder_name" HeaderText="cardholder_name" SortExpression="cardholder_name" />
                            <asp:BoundField DataField="quantities" HeaderText="quantities" SortExpression="quantities" />
                            <asp:BoundField DataField="total_price" HeaderText="total_price" SortExpression="total_price" />
                            <asp:BoundField DataField="date" HeaderText="date" SortExpression="date" />
                            <asp:BoundField DataField="status" HeaderText="status" SortExpression="status" />
                            <asp:BoundField DataField="products" HeaderText="products" SortExpression="products" />
                        </Columns>
                        <EditRowStyle BackColor="#2461BF" />
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EFF3FB" />
                        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F5F7FB" />
                        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                        <SortedDescendingCellStyle BackColor="#E9EBEF" />
                        <SortedDescendingHeaderStyle BackColor="#4870BE" />
                    </asp:GridView>
                        </div>
                <br />
<br />

                    </div>
                
                </div>
            </td>
        </tr>
        
       
    </table>
    
    </asp:Content>

<asp:Content ContentPlaceHolderID="HeaderPlaceHolder" ID="HeaderPlaceID" runat="server">

    <div>
            <asp:DataList ID="DataListHeaderImage" runat="server" DataSourceID="SqlDataSourceHeaderImage" CellPadding="0" HorizontalAlign="Left" RepeatDirection="Horizontal" >
                <ItemTemplate>
                   <a href="Default.aspx"> <asp:Image class="rounded float-left" ID="Image1" runat="server" Height="180px" ImageUrl='<%# Eval("header_image") %>' Width="180px" /><a/>
                    <br />
                        </ItemTemplate>
            </asp:DataList>
        </div>
        <asp:SqlDataSource ID="SqlDataSourceHeaderImage" runat="server" ConnectionString="<%$ ConnectionStrings:RegConnectionString %>" SelectCommand="SELECT [header_image] FROM [Others] WHERE ([other_id] = @other_id)">
            <SelectParameters>
                <asp:Parameter DefaultValue="20" Name="other_id" Type="Int32" />
            </SelectParameters>
        </asp:SqlDataSource>                 
</asp:Content>
<asp:Content ContentPlaceHolderID="BannerPlaceHolder" ID="BannerPlaceId" runat="server">
     
        <div>
            <asp:DataList ID="DataListBannerImage" runat="server" DataSourceID="SqlDataSourceBannerImage" CellPadding="0" HorizontalAlign="right" RepeatDirection="Horizontal" >
                <ItemTemplate>
                    <asp:Image  class="rounded float-right" ID="Image2" runat="server" ImageUrl='<%# Eval("ads_cover_image") %>' height="150px" Width="800px" />
                    <br />
                        </ItemTemplate>
            </asp:DataList>
        </div>
        <asp:SqlDataSource ID="SqlDataSourceBannerImage" runat="server" ConnectionString="<%$ ConnectionStrings:RegConnectionString %>" SelectCommand="SELECT [ads_cover_image] FROM [Others] WHERE ([other_id] = @other_id)">
            <SelectParameters>
                <asp:Parameter DefaultValue="20" Name="other_id" Type="Int32" />
            </SelectParameters>
        </asp:SqlDataSource>

</asp:Content>
<asp:Content ContentPlaceHolderID="goToCartPlaceHolder" ID="cartID" runat="server">
    <asp:Button CausesValidation="false" Font-Size="12" class="btn btn-warning" ID="GoToCart"  runat="server" Text="Go To Cart" OnClick="GoToCart_Click"  />
</asp:Content>