<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="viewCategory.aspx.cs" Inherits="Online_Game_Store.viewCategory" MasterPageFile="~/AdminPanel.Master"  %>

<asp:Content ContentPlaceHolderID="ContentPlaceHolder1" ID="viewCategoryId" runat="server">
        <nav class="navbar navbar-light bg-transparent">   
    <div class="container" >
            <asp:SqlDataSource ID="SqlDataSourceCategory" runat="server" ConnectionString="<%$ ConnectionStrings:RegConnectionString %>" SelectCommand="SELECT * FROM [categories]" UpdateCommand="update [categories] set [category_title]=@category_title where [category_id]=@category_id" DeleteCommand="delete from [categories] where [category_id]=@category_id"></asp:SqlDataSource>
           
            <asp:GridView  ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="category_id" DataSourceID="SqlDataSourceCategory" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="category_id" HeaderText="category_id" InsertVisible="False" ReadOnly="True" SortExpression="category_id" />
                    <asp:BoundField DataField="category_title" HeaderText="category_title" SortExpression="category_title" />
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
             </div>
        </nav>

    </asp:Content>