<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="viewCustomerMessage.aspx.cs" Inherits="Online_Game_Store.viewCustomerMessage" MasterPageFile="~/AdminPanel.Master"  %>
<asp:Content ContentPlaceHolderID="ContentPlaceHolder1" ID="viewCustomerMessageId" runat="server">
       <nav class="navbar navbar-light bg-transparent">   
    <div class="container" >
            <asp:SqlDataSource ID="SqlDataSourceCustomerMessage" runat="server" ConnectionString="<%$ ConnectionStrings:RegConnectionString %>" SelectCommand="SELECT * FROM [help_messages]" UpdateCommand="update [help_messages] set [customer_name]=@customer_name ,[customer_email]=@customer_email,[subject]=@subject,[message]=@message where [Id]=@Id" DeleteCommand="delete from [help_messages] where [Id]=@Id"></asp:SqlDataSource>
            <div style="text-align: left">
            <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSourceCustomerMessage" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="customer_name" HeaderText="customer_name" SortExpression="customer_name" />
                    <asp:BoundField DataField="customer_email" HeaderText="customer_email" SortExpression="customer_email" />
                    <asp:BoundField DataField="subject" HeaderText="subject" SortExpression="subject" />
                    <asp:BoundField DataField="message" HeaderText="message" SortExpression="message" />
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
            </div>
            </div>
        </nav>
</asp:Content>