<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="viewOrders.aspx.cs" Inherits="Online_Game_Store.viewOrders" MasterPageFile="~/AdminPanel.Master" %>



<asp:Content ContentPlaceHolderID="ContentPlaceHolder1" ID="viewCustomersId" runat="server">
       <nav class="navbar navbar-light bg-transparent">   
    
        <asp:SqlDataSource ID="SqlDataSourceOrders" runat="server" ConnectionString="<%$ ConnectionStrings:RegConnectionString %>" SelectCommand="SELECT * FROM [master_card_table]" UpdateCommand="UPDATE [master_card_table] SET [user_id]=@user_id ,[card_number]=@card_number ,[cardholder_name]=@cardholder_name ,[card_address]=@card_address ,[card_mm]=@card_mm ,[card_yy]=@card_yy ,[card_cvc]=@card_cvc ,[quantities]=@quantities ,[total_price]=@total_price ,[date]=@date ,[status]=@status ,[phone_number]=@phone_number ,[products]=@products ,[customer_email]=@customer_email ,[prices]=@prices WHERE [Id]=@Id" DeleteCommand="DELETE FROM [master_card_table] WHERE [Id]=@Id"></asp:SqlDataSource>
        
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataSourceID="SqlDataSourceOrders" ForeColor="#333333" GridLines="None" AutoGenerateColumns="False" DataKeyNames="Id" ShowHeaderWhenEmpty="True">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="user_id" HeaderText="user_id" SortExpression="user_id" />
                    <asp:BoundField DataField="card_number" HeaderText="card_number" SortExpression="card_number" />
                    <asp:BoundField DataField="cardholder_name" HeaderText="cardholder_name" SortExpression="cardholder_name" />
                    <asp:BoundField DataField="card_address" HeaderText="card_address" SortExpression="card_address" />
                    <asp:BoundField DataField="card_mm" HeaderText="card_mm" SortExpression="card_mm" />
                    <asp:BoundField DataField="card_yy" HeaderText="card_yy" SortExpression="card_yy" />
                    <asp:BoundField DataField="card_cvc" HeaderText="card_cvc" SortExpression="card_cvc" />
                    <asp:BoundField DataField="quantities" HeaderText="quantities" SortExpression="quantities" />
                    <asp:BoundField DataField="total_price" HeaderText="total_price" SortExpression="total_price" />
                    <asp:BoundField DataField="date" HeaderText="date" SortExpression="date" />
                    <asp:BoundField DataField="status" HeaderText="status" SortExpression="status" />
                    <asp:BoundField DataField="phone_number" HeaderText="phone_number" SortExpression="phone_number" />
                    <asp:BoundField DataField="products" HeaderText="products" SortExpression="products" />
                    <asp:BoundField DataField="customer_email" HeaderText="customer_email" SortExpression="customer_email" />
                    <asp:BoundField DataField="prices" HeaderText="prices" SortExpression="prices" />
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>

         
        </nav>
</asp:Content>