<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="viewFAQs.aspx.cs" Inherits="Online_Game_Store.viewFAQs" MasterPageFile="~/AdminPanel.Master" %>

<asp:Content ContentPlaceHolderID ="ContentPlaceHolder1" ID="viewFAQID" runat="server">
    <div  class="container">
            <asp:SqlDataSource ID="SqlDataSourcePlatformAll" runat="server" ConnectionString="<%$ ConnectionStrings:RegConnectionString %>" SelectCommand="SELECT * FROM [Faq]" UpdateCommand="Update [Faq] set [Question_1]=@Question_1, [Answer_1]=@Answer_1 where [Id]=@Id" DeleteCommand="Delete from [Faq] where [Id]=@Id"></asp:SqlDataSource>
            <asp:GridView ID="GridViewPlatforms" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSourcePlatformAll" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="Question_1" HeaderText="Question_1" SortExpression="Question_1" />
                    <asp:BoundField DataField="Answer_1" HeaderText="Answer_1" SortExpression="Answer_1" />
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
        </div>

</asp:Content>


