<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="viewCustomer.aspx.cs" Inherits="Online_Game_Store.Manager" MasterPageFile="~/AdminPanel.Master" %>


<asp:Content ContentPlaceHolderID="ContentPlaceHolder1" ID="viewCustomersId" runat="server">
       <nav class="navbar navbar-light bg-transparent">   
    
        <asp:SqlDataSource ID="CustomerDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:RegConnectionString %>" SelectCommand="SELECT * FROM [customer]" UpdateCommand="update [customer] set [customer_name]=@customer_name ,[customer_email]=@customer_email,[customer_pass]=@customer_pass,[customer_country]=@customer_country,[customer_city]=@customer_city,[customer_contact]=@customer_contact,[customer_address]=@customer_address,[customer_gender]=@customer_gender,[customer_s_question]=@customer_s_question,[customer_s_answer]=@customer_s_answer where [customer_id]=@customer_id" DeleteCommand="delete from [customer] where [customer_id]=@customer_id">
            <DeleteParameters>
                <asp:Parameter Name="customer_id" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:Parameter Name="customer_name" />
                <asp:Parameter Name="customer_email" />
                <asp:Parameter Name="customer_pass" />
                <asp:Parameter Name="customer_country" />
                <asp:Parameter Name="customer_city" />
                <asp:Parameter Name="customer_contact" />
                <asp:Parameter Name="customer_address" />
                <asp:Parameter Name="customer_gender" />
                <asp:Parameter Name="customer_id" />
            </UpdateParameters>
           </asp:SqlDataSource>
        
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="customer_id" DataSourceID="CustomerDataSource" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" CellPadding="4" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="customer_id" HeaderText="customer_id" InsertVisible="False" ReadOnly="True" SortExpression="customer_id" />
                <asp:BoundField DataField="customer_name" HeaderText="customer_name" SortExpression="customer_name" />
                <asp:BoundField DataField="customer_email" HeaderText="customer_email" SortExpression="customer_email" />
                <asp:BoundField DataField="customer_pass" HeaderText="customer_pass" SortExpression="customer_pass" />
                <asp:BoundField DataField="customer_country" HeaderText="customer_country" SortExpression="customer_country" />
                <asp:BoundField DataField="customer_city" HeaderText="customer_city" SortExpression="customer_city" />
                <asp:BoundField DataField="customer_contact" HeaderText="customer_contact" SortExpression="customer_contact" />
                <asp:BoundField DataField="customer_address" HeaderText="customer_address" SortExpression="customer_address" />
                <asp:BoundField DataField="customer_gender" HeaderText="customer_gender" SortExpression="customer_gender" />
                <asp:BoundField DataField="customer_s_question" HeaderText="customer_s_question" SortExpression="customer_s_question" />
                <asp:BoundField DataField="customer_s_answer" HeaderText="customer_s_answer" SortExpression="customer_s_answer" />
            </Columns>
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>

         
        </nav>
</asp:Content>